server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=payment_service
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Options: validate | update | create | create-drop
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296